First commit
SBlinsk/window-installation-website pull request #1
Opened 2023-09-02 13:13 UTC by SBlinsk

Start

2023-09-04 16:19 UTC, dkhovrich commented
Папки vite-project не должно быть. Все файлы из нее должны лежать в корне проекта.

2023-09-04 16:20 UTC, dkhovrich commented
Папку .vscode лучше добавить в gitignore.

2023-09-04 16:21 UTC, dkhovrich commented
Файл .DS_Store тоже в gitignore. Это системный скрытый файл, который создает файловая система мак ос.

2023-09-04 16:22 UTC, dkhovrich requested changes
- Папки vite-project не должно быть. Все файлы из нее должны лежать в корне проекта.
- Папку .vscode лучше добавить в gitignore.
- Файл .DS_Store тоже в gitignore. Это системный скрытый файл, который создает файловая система мак ос.

2023-09-13 12:29 UTC, SBlinsk commented
Everything was done. Please approve=)

2023-09-13 12:34 UTC, dkhovrich requested changes

2023-09-13 12:34 UTC, dkhovrich commented on .gitignore
> +.DS_Store/
Это файл а не директория, так что просто `.DS_Store`

2023-09-13 13:03 UTC, SBlinsk commented on .gitignore
> +.DS_Store/
Done

2023-09-13 13:09 UTC, dkhovrich approved these changes

2023-09-13 13:18 UTC, merged