Added component Glazing, glazingData, GlazingSlider
SBlinsk/window-installation-website pull request #2
Opened 2023-09-15 13:11 UTC by SBlinsk

2023-09-17 20:23 UTC, dkhovrich requested changes

2023-09-17 20:23 UTC, dkhovrich commented on src/assets/css/style.css
> +.glazing_slider {
Один большой файл с css для всех компонентов - плохая практика. Если эти стили относятся к компоненту Glazing, то файл css должен находиться в той же директории, что и JSX. И обычно его импортируют в компоненте первой строчкой:` import "./style.css"`

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/glazingData.jsx
Неправильное расширение файла. Тут достаточно js. jsx не нужен.

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +    const selItem = data.find((item) => item.id === ids);
setItem - плохое имя. старайся не использовать сокращения в именах переменных

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +    const selItem = data.find((item) => item.id === ids);
Ф-ция findGlazingDataById не работает с состоянием компонента, поэтому ее вполне можно вынести за пределы компонента Glazing.

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +  useEffect(() => {
Этот эффект не нужен. Как и useState выше. Вычисляемое состояние не нужно хранить в useState и уж тем более вычислять в useEffect.

Достаточно будет просто сделать так:
`const selectedItem = findGlazingDataById(selectedImageId);`

Если вдруг там будут тысячи записей, то можно завернуть в useMemo. Но в твоем случае это лишнее.

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +const ViewItem = ({item}) => {
В этом компоненте очень много верстки. Посмотри можно ли вынести часть этой верстки в отдельные компоненты. Это улучит читабельность и поможет потом повторно использовать код.

Точно стоит вынести в отдельный компонент `<button>`. `<img>` тоже кандидат.

2023-09-17 20:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +  const data = glazingData;
Данные в такие компоненты лучше передавать через props снаружи.

2023-09-20 11:02 UTC, SBlinsk commented on src/assets/css/style.css
> +.glazing_slider {
Да, я знаю, но это не мои стили. Заготовка проекта была сверстана на  HTML, CSS. Я лишь переписываю ее на реакт, добавляя интерактивности. Не хотел тратить время на стили.=)

2023-09-20 11:04 UTC, SBlinsk commented on src/components/Glazing/glazingData.jsx
Так и было, но начало выдавать ошибки, типа все должны быть одного расширения. Изначально было   js

2023-09-20 11:05 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +    const selItem = data.find((item) => item.id === ids);
Понял, испарвил

2023-09-20 12:47 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +  useEffect(() => {
Done/ Я переделал, но мне поему-то показалось, что надо передавать в стейт, чтобы потом манипулировать с модальным окном передавая стейт дальше в компоненты.

2023-09-20 12:47 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +const ViewItem = ({item}) => {
Не совсем понимаю зачем переделывть img на компонент, ведь колличество строк не поменялось) Пути к картинке все равно надо передавать через пропсы. Сделал.

2023-09-20 12:47 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +  const data = glazingData;
Done/ Почему?

2023-09-20 13:06 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +  const data = glazingData;
Чтобы их можно было повторно использовать в другом месте. Понимаю что в твоем случае это не нужно, но это хорошая практика.

2023-09-20 13:07 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +  const data = glazingData;
=)

2023-09-20 13:07 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +const ViewItem = ({item}) => {
Дело не в количестве строк, а в переиспользовании поведения. Вот пример подобного компонента. Он добавляет картинке анимацию загрузки и fadein анимацию отображения.
https://www.npmjs.com/package/material-ui-image

2023-09-20 13:10 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +const ViewItem = ({item}) => {
Понял, это типа заготовка для того, чтобы можно было модернизировать кнопку в отдельном компоненте

2023-09-20 13:14 UTC, dkhovrich requested changes

2023-09-20 13:14 UTC, dkhovrich commented on src/App.jsx
> +      <Glazing dataOfGlazing ={glazingData}/>
В имени пропсы дублируется контекст. Просто `data` было бы достаточно.

2023-09-20 13:14 UTC, dkhovrich commented on src/components/Glazing/Button.jsx
> +      Рассчитать стоимость
Текст должен передаваться снаружи. Можно через children.
`<Button>Шура</Button>`

2023-09-20 13:14 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +        {modal ? <ModalCalc modalClose={modalClose} /> : null}
Попридираюсь к неймингу
nit: `{hasModal && <Modal onClose={closeModal}}`

2023-09-20 13:14 UTC, dkhovrich commented on src/components/modalCalc/modalCalc.jsx
> +const ModalCalc = ({ isOpen, price, onClose }) => {
Попробуй разделить это на две части:
1. Компонент Modal. Он отвечает за модалку, за ее отображение и стили. Не содержит контента. Может отрисовывать кнопку закрытия (кретик в углу, зависит от дизайна)
2. Компонент, в котором находится UI для подсчета площади. 

Использоваться будет как-то так:
```
<Modal isOpen={isOpen} onClose={onClose}>
<Footage onChange={onChange} />
</Modal>
```

2023-09-20 13:20 UTC, SBlinsk commented on src/App.jsx
> +      <Glazing dataOfGlazing ={glazingData}/>
Да, но там потом в самом компоненте есть data  и выдается ошика по несовместимости. Ну назовут как-то коротко)

2023-09-20 13:25 UTC, dkhovrich commented on src/App.jsx
> +      <Glazing dataOfGlazing ={glazingData}/>
Ты про это? Оно не нужно. Можно напрямую использовать data, который из пропсов.
`const data = dataOfGlazing;`

2023-09-21 14:11 UTC, SBlinsk commented on src/components/modalCalc/modalCalc.jsx
> +const ModalCalc = ({ isOpen, price, onClose }) => {
Done

2023-09-21 14:11 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +        {modal ? <ModalCalc modalClose={modalClose} /> : null}
Done

2023-09-21 14:11 UTC, SBlinsk commented on src/components/Glazing/Button.jsx
> +      Рассчитать стоимость
Done

2023-09-21 14:11 UTC, SBlinsk commented on src/App.jsx
> +      <Glazing dataOfGlazing ={glazingData}/>
Да, понял, переделал)

2023-09-21 17:23 UTC, dkhovrich approved these changes

2023-09-21 17:23 UTC, dkhovrich commented on src/components/Glazing/Glazing.jsx
> +  const selecledItem = findGlazingDataById(selectedImageId, dataArr);
`const selecledItem = findGlazingDataById(selectedImageId, data);`
И эту строчку можно будет удалить: `const dataArr = data;`
Не вижу чтобы `dataArr` использовалась бы где-то еще.

2023-09-22 11:02 UTC, SBlinsk commented on src/components/Glazing/Glazing.jsx
> +  const selecledItem = findGlazingDataById(selectedImageId, dataArr);
Done

2023-09-22 11:02 UTC, merged